name = "well-known"
type = "javascript"
zone_id = ""
account_id = "77a37d339acf8213d7263e5bf351ef40"
route = ""
workers_dev = true
compatibility_date = "2022-01-13"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"


[env.production]
# The ID of the domain to deploying to
zone_id = "365f57d6577c17f5cbab2739bd3530fc"

# The route pattern your Workers application will be served at
route = "atunemic.cn/.well-known/matrix/*"
